jwt:
  issuer: platform_admin_issuer                 # 该JWT的签发者
  audience: platform_admin_audience             # 该JWT的验证者
  expiresInMinute: 600                        # 该JWT的有效分钟数
  signKey: NvLVyY}rf4ZmXLZ?]w@sq.63AuJmUNqU   # 签名key
